spring:
    profiles: dev
logging:
    level:
        org.springframework.web: INFO
        org.hibernate: INFO 
    file: ${my.log}
    jpa:
        hibernate:
            show-sql: true
server:
    port: 9001